

/****** Object:  Database [Db_RoadData]    Script Date: 18-09-2021 12:39:11 ******/
CREATE DATABASE [Db_RoadData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Db_RoadData', FILENAME = N'E:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Db_RoadData.mdf' , SIZE = 466944KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Db_RoadData_log', FILENAME = N'E:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Db_RoadData_log.ldf' , SIZE = 1122304KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Db_RoadData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Db_RoadData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Db_RoadData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Db_RoadData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Db_RoadData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Db_RoadData] SET ARITHABORT OFF 
GO

ALTER DATABASE [Db_RoadData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Db_RoadData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Db_RoadData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Db_RoadData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Db_RoadData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Db_RoadData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Db_RoadData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Db_RoadData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Db_RoadData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Db_RoadData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Db_RoadData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Db_RoadData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Db_RoadData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Db_RoadData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Db_RoadData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Db_RoadData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Db_RoadData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Db_RoadData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Db_RoadData] SET  MULTI_USER 
GO

ALTER DATABASE [Db_RoadData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Db_RoadData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Db_RoadData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Db_RoadData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Db_RoadData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Db_RoadData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Db_RoadData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Db_RoadData] SET  READ_WRITE 
GO


